working_directory = 'C:\'

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 300

[font]
size = 10

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[font.offset]
x = 1
y = 0

[[keyboard.bindings]]
chars = "cls"
key = "L"
mods = "Control"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
args = ["--cd c:/"]
program = "cmd.exe"

[window.padding]
x = 4
y = 1


# Default colors
[colors.primary]
background = '#15141b'
foreground = '#edecee'

# Normal colors
[colors.normal]
black   = '#110f18'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

# Bright colors
[colors.bright]
black   = '#4d4d4d'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

[colors.selection]
text       = 'CellForeground'
background = '#29263c'

[cursor]
style = "Beam"
unfocused_hollow = true

[colors.cursor]
cursor = '#a277ff'
