import = [
	#"~\\AppData\\Roaming\\alacritty\\themes\\dawnfox.toml"
	#"~\\AppData\\Roaming\\alacritty\\themes\\default.toml"
	"~\\AppData\\Roaming\\alacritty\\themes\\github_light.toml"
]

working_directory = 'C:\'

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 300

[font]
size = 10

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[font.offset]
x = 1
y = 0

[[keyboard.bindings]]
chars = "cls"
key = "L"
mods = "Control"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
args = ["--cd c:/"]
program = "cmd.exe"

[window.padding]
x = 4
y = 1

