theme = "default"

[editor]
line-number = "absolute"
mouse = true
cursorcolumn = false
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
C-s = ":w"