theme = "helix_dark"

[editor]
line-number = "absolute"
mouse = true
cursorcolumn = false
cursorline = true
gutters = ["diff", "line-numbers", "spacer"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
C-s = ":w"
C-v = "paste_clipboard_before"
C-c = ":clipboard-yank"
C-z = "undo"
C-y = "redo"
C-a = "select_all"
C-q = "toggle_comments"

[keys.insert]
C-s = ":w!"
C-v = "paste_clipboard_before"
C-a = "select_all"
C-q = "toggle_comments"

[keys.select]
C-c = ":clipboard-yank"
C-q = "toggle_comments"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORM"
mode.insert = "INSR"
mode.select = "SELT"
