# Author: knoxydev

"ui.background" = {bg="black"}
"ui.text" = "white"
"ui.linenr" = {bg="black", fg="#404040"}
"ui.linenr.selected" = {bg="black", fg="white"}
"ui.selection" = {bg="white", fg="black"}
"ui.statusline" = { fg="#565656", bg="black" }
"ui.statusline.inactive" = {fg="black", bg="acme_bar_inactive"}
"ui.virtual" = "indent"
"ui.virtual.ruler" = { bg = "#223B3B" }
"ui.virtual.indent-guide" = { fg = "#212121" }


"ui.cursor.match" = { fg = "red" }
"ui.cursorline.primary" = { bg = "#121212" }


"ui.debug" = {fg="orange"}
"ui.highlight.frameline" = {bg="#da8581"}


"type" = "#19BE6A"
"type.builtin" = "#19BE6A"
"string" = "red"
"comment" = "#404040"
"constant" = "#EE3732"
"function.macro" = "#9282EE"
"keyword.control.conditional" = "#05BDBA"
"keyword.control.repeat" = "#05BDBA"
"keyword.control.return" = "#05BDBA"
"keyword.control.import" = "#05BDBA"
"keyword.function" = "#05BDBA"
"keyword.storage" = "#05BDBA"
"keyword" = "#05BDBA"


"ui.help" = {fg="white", bg="#1E1E1E"}
"ui.popup" = {fg="black", bg="#1E1E1E"}
"ui.menu" = {fg="white", bg="#1E1E1E"}
"ui.menu.selected" = {bg="acme_bg", fg="black"}
"ui.window" = {bg="acme_bg"}
"diagnostic.error" = {bg="red", fg="white", modifiers=["bold"]}
"diagnostic.warning" = {bg="orange", fg="black", modifiers=["bold"]}
"diagnostic.hint" = {fg="gray", modifiers=["bold"]}
"ui.bufferline" = { fg = "black", bg = "acme_bar_bg" }
"ui.bufferline.active" = { fg = "black", bg = "acme_bg" }
"diff.plus" = {fg = "green"}
"diff.delta" = { fg = "black" }
"diff.minus" = {fg = "red"}

[palette]
white = "#ffffff"
acme_bg = "#ffffea"
black = "#000000"
selected = "#eeee9e"
acme_bar_bg = "#375F5F"
acme_bar_inactive = "#eaffff"
cursor = "#444444"
red = "#a0342f"
green = "#065905"
indent = "#aaaaaa"
orange = "#f0ad4e"
gray = "#777777"

