# Author: knoxydev

"ui.background" = {bg="black"}
"ui.text" = "white"
"ui.linenr" = {bg="black", fg="#404040"}
"ui.linenr.selected" = {bg="#121212", fg="white"}
"ui.selection" = {bg="white", fg="black"}
"ui.statusline" = { fg="#565656", bg="black" }
"ui.statusline.inactive" = {fg="black", bg="acme_bar_inactive"}
"ui.virtual" = "indent"
"ui.virtual.ruler" = { bg = "#223B3B" }
"ui.virtual.indent-guide" = { fg = "#212121" }


"ui.cursor.match" = { fg = "white", bg = "red" }
"ui.cursorline.primary" = { bg = "#121212" }


"ui.debug" = {fg="orange"}
"ui.highlight.frameline" = {bg="#da8581"}


"type" = "type_clr"
"type.builtin" = "type_clr"
"string" = "str"
"punctuation.bracket" = "bracket_clr"
"comment" = "#404040"
"constant" = "str"
"function.macro" = "#9282EE"
"keyword.control.conditional" = "main_clr"
"keyword.control.repeat" = "main_clr"
"keyword.control.return" = "main_clr"
"keyword.control.import" = "main_clr"
"keyword.function" = "main_clr"
"keyword.storage" = "main_clr"
"keyword" = "main_clr"


"ui.help" = {fg="white", bg="black"}
"ui.popup" = {fg="white", bg="black"}
"ui.menu" = {fg="white", bg="black"}
"ui.menu.selected" = {bg="acme_bg", fg="black"}
"ui.window" = {bg="acme_bg"}
"diagnostic.error" = {bg="red", fg="white", modifiers=["bold"]}
"diagnostic.warning" = {bg="orange", fg="black", modifiers=["bold"]}
"diagnostic.hint" = {fg="gray", modifiers=["bold"]}
"ui.bufferline" = { fg = "black", bg = "acme_bar_bg" }
"ui.bufferline.active" = { fg = "black", bg = "acme_bg" }
"diff.plus" = {fg = "green"}
"diff.delta" = { fg = "black" }
"diff.minus" = {fg = "red"}

[palette]
white = "#ffffff"
acme_bg = "#ffffea"
black = "#000000"
selected = "#eeee9e"
acme_bar_bg = "#375F5F"
acme_bar_inactive = "#eaffff"
cursor = "#444444"
red = "#a0342f"
green = "#065905"
indent = "#aaaaaa"
orange = "#f0ad4e"
gray = "#777777"
main_clr = "#00FFD0" #05BDBA
bracket_clr = "#999999"
str = "#F36791" #FF456F
type_clr = "#28CD79" #19BE6A
