# Author: knoxydev

"ui.background" = {bg="prpl_bg"}
"ui.text" = "white"
"ui.linenr" = {bg="prpl_bg", fg="grey_one"}
"ui.linenr.selected" = {bg="line_bg", fg="white"}
"ui.selection" = {bg="#8C00FF", fg="white"}
"ui.statusline" = { fg="prpl_light", bg="prpl_darker" }
"ui.statusline.inactive" = {fg="black", bg="acme_bar_inactive"}
"ui.virtual" = "indent"
"ui.virtual.ruler" = { bg = "#223B3B" }
"ui.virtual.indent-guide" = { fg = "darker_grey" }

"ui.cursor" = { bg = "red" }
"ui.cursor.match" = { fg = "prpl_darker", bg = "prpl_light" }
"ui.cursorline.primary" = { bg = "line_bg" }
"ui.cursorline.secondary" = { bg = "line_bg" }
"ui.cursorcolumn.secondary" = { bg = "red" }

"ui.debug" = {fg="orange"}
"ui.highlight.frameline" = {bg="#da8581"}


"type" = "white"
"type.builtin" = "white"
"string" = "#FFB2B2"
"comment" = "grey_one"
"constant" = "yellow_light_two"
"function.macro" = "#9282EE"
"function.method" = "red"
"keyword.control.conditional" = "main_color"
"keyword.control.repeat" = "main_color"
"keyword.control.return" = "main_color"
"keyword.control.import" = "main_color"
"keyword.function" = "main_color"
"keyword.storage" = "main_color"
"keyword" = "main_color"
"punctuation.bracket" = "bracket_color"
"variable" = "bracket_color"
"namespace" = "prpl_light"


"ui.help" = {fg="black", bg="#7958DC"}
"ui.popup" = {fg="white", bg="prpl_darker"}
"ui.menu" = {fg="prpl_light", bg="prpl_darker"}
"ui.menu.selected" = {bg="acme_bg", fg="black"}
"ui.window" = {bg="acme_bg"}
"diagnostic.error" = {bg="red", fg="white", modifiers=["bold"]}
"diagnostic.warning" = {bg="orange", fg="black", modifiers=["bold"]}
"diagnostic.hint" = {fg="gray", modifiers=["bold"]}
"ui.bufferline" = { fg = "black", bg = "acme_bar_bg" }
"ui.bufferline.active" = { fg = "black", bg = "acme_bg" }
"diff.plus" = {fg = "green"}
"diff.delta" = { fg = "black" }
"diff.minus" = {fg = "red"}


[palette]
white = "#ffffff"
acme_bg = "#ffffea"
black = "#000000"
selected = "#eeee9e"
acme_bar_bg = "#375F5F"
acme_bar_inactive = "#eaffff"
cursor = "#444444"
red = "#a0342f"
green = "#065905"
indent = "#aaaaaa"
orange = "#f0ad4e"
gray = "#777777"

prpl_bg = "#2F1B3D"
prpl_light = "#DBBCE9"
prpl_darker = "#281733"
yellow_light = "#ECB28A"
grey_one = "#565777"
darker_grey = "#484969"
main_color = "#ECC9AA"
yellow_light_two = "#E8DC9D"
bracket_color = "#A2A0E8"
line_bg = "#452859"

